### PR TITLE
Add zoom config in preprocessing when using per_patch

### PR DESCRIPTION
**Pull request by ClementCaporal**

### CODE REVIEW

**Comment by danifranco** [comment]
Hello! Thank you so much for doing these changes Clement!
I have a suggestion here:
- Change please the variable name to ``_C.DATA.PREPROCESS.ZOOM`` to follow the same preprocessing convention we are already using. Even if the zoom can only be aplied when predicting ``by_chunks`` I would do that way. I'd put in it's comment/description above a message warning the user that is only enabled in that case (see other cases in `config.py` that are described like that so you can follow the same message structure in case you have doubts). E.g. for Canny preprocessing this is hwo it's done: https://github.com/BiaPyX/BiaPy/blob/f872e1fd74fe55b66c694ef0289bb07495265c5f/biapy/config/config.py#L320

**Comment by ClementCaporal** [comment]
Hello thank you for your review @danifranco
I changed the structure as requested. Tell me if I can do something else to match BiaPy pattern.

**Comment by danifranco** [comment]
Just few minro things more:
- Add an example on how to use that in `DATA.PREPROCESS.ZOOM.ZOOM_FACTOR` above description please. Like: "E.g. [1,2,2,2,3] that needs to match Zarr axes"? or something like that. 
- It's length is related to `TEST.BY_CHUNKS.INPUT_IMG_AXES_ORDER` or `TEST.BY_CHUNKS.INPUT_MASK_AXES_ORDER`? If so put a check in [check_configuration.py](https://github.com/BiaPyX/BiaPy/blob/master/biapy/engine/check_configuration.py) please.

**Comment by ClementCaporal** [comment]
Hello !

- I added an example in the description
- I added a configuration check to raise an error if the zoom factor is not the same size than the img_axes_order

**Pull request merged**
